#!/bin/bash

# Massimo Lauria, 2010, 2011, 2012, 2013, 2015
#
# Common enviroment variables to be loaded in bash, zsh, X11, ...
#

# Where everything starts
CONFIGDIR=$HOME/config

# {{{ Paths --------------------------------------------------------------------

# Those are useful for MacPorts
if [ -d /opt/local/bin ]; then
    PATH=/opt/local/bin:$PATH
fi
if [ -d /opt/local/sbin ]; then
    PATH=/opt/local/sbin:$PATH
fi
export PATH

# ~/.local/ paths
if [ -d $HOME/.local/bin ]; then
    PATH=$HOME/.local/bin:$PATH
fi
if [ -d $HOME/.local/sbin ]; then
    PATH=$HOME/.local/sbin:$PATH
fi
export PATH

# MacOSX substitute for `~/.local/bin` could be `~/Library/bin'? 
if [ -d $HOME/Library/bin ]; then
    PATH=$HOME/Library/bin:$PATH
fi


# }}} --------------------------------------------------------------------------



# {{{ Pager --------------------------------------------------------------------
if [[ -f `which most 2>/dev/null` ]]; then
    PAGER=most
elif [[ -f `which less 2>/dev/null` ]]; then
    PAGER=less
else
    PAGER=more
fi
export PAGER
# }}} --------------------------------------------------------------------------




### Include other files
source $CONFIGDIR/shell/shenv-emacs
source $CONFIGDIR/shell/shenv-gnupg
source $CONFIGDIR/shell/shenv-mitscheme
source $CONFIGDIR/shell/shenv-latex
source $CONFIGDIR/shell/shenv-python
source $CONFIGDIR/shell/shenv-haskell
source $CONFIGDIR/shell/shenv-repository


if [ -f "$HOME/personal/conf/shenv-personal" ]; then
	source $HOME/personal/conf/shenv-personal
fi

if [ x`uname` = "xDarwin" ]; then
    source $CONFIGDIR/shell/shenv-macosx
fi

## Umask
umask 0077

## We don't need start/stop terminal
stty stop  '^q'
stty start '^q'
