#!/bin/sh

# Massimo Lauria, 2010
#
# Shell commands for MacOSX. This is because MacOSX has no Xsession.
#

## SSH identity load
if [ -n "$SSHIDENTITY" -a -f $SSHIDENTITY ]; then
    ssh-add $SSHIDENTITY 2> /dev/null
fi

## Dircolors in not installed by defauls in Mac,
## and ls utility is not the GNU one by default.
CLICOLOR=1
LSCOLORS=ExFxCxDxBxegedabagacad
export CLICOLOR LSCOLORS
