#!/bin/sh

# Massimo Lauria, 2010, 2011, 2012, 2013, 2015
#
# Common enviroment variables to be loaded in bash, zsh, X11, ...
#

# Where everything starts
CONFIGDIR=$HOME/config

# Unfortunately I cannot make MacOSX to load .profile file on login
if [ `uname` = "Darwin" -a -f ~/.profile ]; then
    source ~/.profile
fi

# {{{ Paths --------------------------------------------------------------------

# Flatpak
if [ -d /var/lib/flatpak/exports/bin/ ]; then
    PATH=/var/lib/flatpak/exports/bin/:$PATH
fi

# MacPorts binary path
if [ -d /opt/local/bin ]; then
    PATH=/opt/local/bin:$PATH
fi
if [ -d /opt/local/sbin ]; then
    PATH=/opt/local/sbin:$PATH
fi

# Brew binary path
if [ -d /usr/local/bin ]; then
    PATH=/usr/local/bin:$PATH
fi
if [ -d /usr/local/sbin ]; then
    PATH=/usr/local/sbin:$PATH
fi

# ~/.local/ paths
if [ -d $HOME/.local/bin ]; then
    PATH=$HOME/.local/bin:$PATH
fi
if [ -d $HOME/.local/sbin ]; then
    PATH=$HOME/.local/sbin:$PATH
fi

if [ -d $HOME/.elan/bin ]; then
    PATH=$HOME/.elan/bin:$PATH
fi
export PATH

# MacOSX substitute for `~/.local/bin` could be `~/Library/bin'?
if [ -d $HOME/Library/bin ]; then
    PATH=$HOME/Library/bin:$PATH
fi

# Rust cargo binaries
if [ -d $HOME/.cargo/bin ]; then
    PATH=$HOME/.cargo/bin:$PATH
fi

# }}} --------------------------------------------------------------------------



### Include other files
sh_sources=${CONFIGDIR}/shell/sh.d/

for sh_snippet in $sh_sources/*.sh; do
    source $sh_snippet
done


if [ -f "$HOME/personal/conf/shenv-personal" ]; then
	source $HOME/personal/conf/shenv-personal
fi


if [ -f "$HOME/games/shenv" ]; then
	source $HOME/games/shenv
fi


## Umask
umask 0077

## We don't need start/stop terminal
stty stop  '^q'
stty start '^q'
